
    const data ={
        serviceeee:[
            {
            "service": "212",
            "name": "\u23e9FAST\ud83c\uddee\ud83c\uddf3 100 % Indian Followers -Non Drop & 365 days refillable",
            "category": "\ud83c\uddee\ud83c\uddf3lNDIAN WOW SPEED\ud83c\uddee\ud83c\uddf3",
            "rate": "65.4300",
            "min": "1000",
            "max": "100000",
            "type": "default",
            "desc": "Start: 0 - 10 Min\ud83d\ude0e\r\n Speed: 50K+ \/Day\ud83d\ude0d\r\n Quality: Indian Profile\ud83c\uddee\ud83c\uddf3\r\n Mostly Non Dro\u2611\r\n Refill:365 Day Refill\ud83d\ude31\ud83d\ude31\ud83d\ude31\r\nAlmost all Profiles have Profile picture\r\n",
            "dripfeed": "0"
            },
            {
            "service": "205",
            "name": "\ud83d\udcf8 IG Views + Tv + Reels | \u23e9 10-20k per Day | \u25b6\ufe0f Start: 0-1Hours",
            "category": "\ud83d\udd35OFFICIALSMM WORKING VIEWS \ud83d\udc41\ufe0f\ud83d\udc41\ufe0f",
            "rate": "0.6600",
            "min": "100",
            "max": "300000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "206",
            "name": "\ud83d\udcf8 IG Views + Tv + Reels | \u2764\ufe0f\u200d\ud83d\udd25 Cheapest & Fast | \u25b6\ufe0f Start: 0-6 Hours",
            "category": "\ud83d\udd35OFFICIALSMM WORKING VIEWS \ud83d\udc41\ufe0f\ud83d\udc41\ufe0f",
            "rate": "0.8800",
            "min": "100",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "147",
            "name": "\ud83d\udcf8 IG Views + Tv + Reels | \u23e9Fast | \u25b6\ufe0f Start: Instant",
            "category": "\ud83d\udd35OFFICIALSMM WORKING VIEWS \ud83d\udc41\ufe0f\ud83d\udc41\ufe0f",
            "rate": "1.0100",
            "min": "100",
            "max": "50000000",
            "type": "default",
            "desc": "\r\n\u25b6\ufe0f Start: 0-1 Hours\r\n\u23e9 Speed: +50K Per Day\r\n\ud83d\udd25 Quality: Real\r\n\ud83d\udca7 Drop: Non Drop\r\n\ud83d\udd87\ufe0f Link: Reel, Video, Igtv All Link Works\r\n\u2714\ufe0f Order again if you can complete one order",
            "dripfeed": "0"
            },
            {
            "service": "207",
            "name": "\ud83d\udcf8 IG Views + Tv + Reels | \u2764\ufe0f\u200d\ud83d\udd25 Cheapest | \u25b6\ufe0f Start: Instant",
            "category": "\ud83d\udd35OFFICIALSMM WORKING VIEWS \ud83d\udc41\ufe0f\ud83d\udc41\ufe0f",
            "rate": "1.2600",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "146",
            "name": "\ud83d\udc41\ufe0f\ud83d\udc41\ufe0f IG Views + Tv + Reels +\u00a0Cheapest | \ud83d\udc4d\u00a0Start: 0-1 Hours",
            "category": "\ud83d\udd35OFFICIALSMM WORKING VIEWS \ud83d\udc41\ufe0f\ud83d\udc41\ufe0f",
            "rate": "1.7500",
            "min": "100",
            "max": "5000000",
            "type": "default",
            "desc": "\ud83d\udc49\ud83c\udffb\ud835\ude4e\ud835\ude69\ud835\ude56\ud835\ude67\ud835\ude69: 0-6  Hours\r\n\ud83d\udc49\ud83c\udffb\ud835\ude4e\ud835\ude65\ud835\ude5a\ud835\ude5a\ud835\ude59: fast\r\n\ud83d\udc49\ud83c\udffb\ud835\ude4c\ud835\ude6a\ud835\ude56\ud835\ude61\ud835\ude5e\ud835\ude69\ud835\ude6e: Real\r\n\ud83d\udc49\ud83c\udffb\ud835\ude4d\ud835\ude5a\ud835\ude5b\ud835\ude5e\ud835\ude61\ud835\ude61: No\r\n\ud83d\udc49\ud83c\udffb\ud835\ude3f\ud835\ude67\ud835\ude64\ud835\ude65: Non Drop\r\n---------------------------\r\n\ud83d\udd17Example link: https:\/\/www.instagram.com\/abcxyz\r\n---------------------------\r\n\ud83d\udd25 Support on the server is good",
            "dripfeed": "0"
            },
            {
            "service": "148",
            "name": "\u2763\ud835\ude10\ud835\ude15\ud835\ude1a\ud835\ude1b\ud835\ude08\ud835\ude0e\ud835\ude19\ud835\ude08\ud835\ude14 LIKE || BOT \u2620 || ~\u3010NO REFILL\u3011",
            "category": "\u2764 Instagram Likes (No Refill )",
            "rate": "3.8500",
            "min": "10",
            "max": "30000",
            "type": "default",
            "desc": "\r\n\r\n\r\n\ud83d\udc49\ud83c\udffb\ud835\ude4e\ud835\ude4f\ud835\ude3c\ud835\ude4d\ud835\ude4f\ud835\ude4f\ud835\ude44\ud835\ude48\ud835\ude40:INSTANT\r\n\r\n\ud83d\udc49\ud83c\udffb\ud835\ude4e\ud835\ude4b\ud835\ude40\ud835\ude40\ud835\ude3f:1K-5K \/Day\r\n\r\n\ud83d\udc49\ud83c\udffb\ud835\ude42\ud835\ude50\ud835\ude3c\ud835\ude4d\ud835\ude3c\ud835\ude49\ud835\ude4f\ud835\ude40\ud835\ude40\ud835\ude3f:NO REFILL\r\n\r\n\ud83d\udc49\ud83c\udffb\ud835\ude4c\ud835\ude50\ud835\ude3c\ud835\ude47\ud835\ude44\ud835\ude4f\ud835\ude54:REAL HQ BOT",
            "dripfeed": "0"
            },
            {
            "service": "145",
            "name": "Instagram Bot Likes Max 10K",
            "category": "\u2764 Instagram Likes (No Refill )",
            "rate": "5.3200",
            "min": "10",
            "max": "10000",
            "type": "default",
            "desc": "Speed:1K In 1Min\r\n20-50%+ Drop\r\nNO REFILL\r\nCancel Button Enabled",
            "dripfeed": "0"
            },
            {
            "service": "129",
            "name": "\ud83c\uddee\ud83c\uddf3 Instagram Likes | INDIAN Mixed | Good Quality | 0-5% Drop | No Refill",
            "category": "\u2764 Instagram Likes (No Refill )",
            "rate": "6.8400",
            "min": "10",
            "max": "15000",
            "type": "default",
            "desc": "Ultra fast \u26a1\r\nMay drop 0 - 5% sometimes \ud83d\udd3d\r\nNo Refill \u267b",
            "dripfeed": "0"
            },
            {
            "service": "83",
            "name": "\u26a1Instagram Likes Bots (Max:10K) | No Refill |\u26a1SuperFast | \u274cCancel button \u2705",
            "category": "\u2764 Instagram Likes (No Refill )",
            "rate": "8.7400",
            "min": "10",
            "max": "15000",
            "type": "default",
            "desc": "No guarantee\r\nfull drop may be seen\r\n-0-1hr start\r\nLQ",
            "dripfeed": "1"
            },
            {
            "service": "33",
            "name": "\ud83c\udd95 IGTV Views [Real] [Non Drop] FAST \ud83d\ude85\u2b50",
            "category": "\ud83d\udd35 INSTAGRAM VIEWS ",
            "rate": "2.2500",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "NON DROP\r\nINSTANT START\r\nVERY FAST\r\n\r\nDISCOUNT NOT AVAILABLE",
            "dripfeed": "0"
            },
            {
            "service": "140",
            "name": "\u00a0Instagram Superfast Views [Posts Only] Read Discription \u2b07\ufe0f",
            "category": "\ud83d\udd35 INSTAGRAM VIEWS ",
            "rate": "16.7200",
            "min": "100",
            "max": "300000",
            "type": "default",
            "desc": "Emergency views\r\nAdded on 20\/12\/2021 \r\nCopy paste post URL to work in an hour\r\nReels URL takes time\r\nMay stop working at any time\r\nNo speed up, cancelation and no refund will be provided",
            "dripfeed": "0"
            },
            {
            "service": "132",
            "name": "Instagram Working Instant Views",
            "category": "\ud83d\udd35 INSTAGRAM VIEWS ",
            "rate": "39.5200",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "TESTED AND WORKING\r\nDO NOT ASK FOR SPEEDUP",
            "dripfeed": "0"
            },
            {
            "service": "92",
            "name": "Instagram Followers | Real Mixed | max 10k | No Refill\u26d4",
            "category": "\u25b6\u25b6 Instagram: Followers: REAL [ No Refill ]",
            "rate": "23.5600",
            "min": "50",
            "max": "20000",
            "type": "default",
            "desc": "RISKY PACK\r\nNO REFILL\r\nNO REFUND\r\nNO CANCELLATIONS\r\nNO SPEED UP\r\nORDERS MAY GET CANCELLED OR MAY GET DELAY UPTO 4 DAYS\r\nPRICES MAY GO UP AND DOWN AS PER EXCHANGE RATES ",
            "dripfeed": "0"
            },
            {
            "service": "139",
            "name": "Instagram - Followers | MQ 80K | Speed 80K P\/D | Real",
            "category": "\u25b6\u25b6 Instagram: Followers: REAL [ No Refill ]",
            "rate": "23.5600",
            "min": "50",
            "max": "80000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "138",
            "name": "Instagram \ud83e\udd16BOT Followers [Speed 100\/Hrs] [No-refill] Max-10K [0-1Hr Start]",
            "category": "\u25b6\u25b6 Instagram: Followers: REAL [ No Refill ]",
            "rate": "25.0800",
            "min": "50",
            "max": "10000",
            "type": "default",
            "desc": "COMPLETE BOTS FOLLOWERS \ud83e\udd16\r\nMAXIMUM 10K \r\nNO REFILL IF DROPPED",
            "dripfeed": "0"
            },
            {
            "service": "93",
            "name": "Instagram Followers | Real | Max 1k | No Refill |",
            "category": "\u25b6\u25b6 Instagram: Followers: REAL [ No Refill ]",
            "rate": "25.8400",
            "min": "20",
            "max": "1000",
            "type": "default",
            "desc": "RISKY PACK\r\nNO REFILL\r\nNO REFUND\r\nNO CANCELLATIONS\r\nNO SPEED UP\r\nORDERS MAY GET CANCELLED OR MAY GET DELAY UPTO 4 DAYS\r\nPRICES MAY GO UP AND DOWN AS PER EXCHANGE RATES",
            "dripfeed": "0"
            },
            {
            "service": "94",
            "name": "Instagram Followers | Real | Max 80k | 20k-40k\/Day |",
            "category": "\u25b6\u25b6 Instagram: Followers: REAL [ No Refill ]",
            "rate": "26.6000",
            "min": "10",
            "max": "50000",
            "type": "default",
            "desc": "RISKY PACK\r\nNO REFILL\r\nNO REFUND\r\nNO CANCELLATIONS\r\nORDERS MAY GET CANCELLED OR MAY GET DELAY UPTO 4  DAYS\r\nPRICES MAY GO UP AND DOWN AS PER EXCHANGE RATES",
            "dripfeed": "0"
            },
            {
            "service": "204",
            "name": "Instagram Bot Followers Max 10k",
            "category": "\u25b6\u25b6 Instagram: Followers: REAL [ No Refill ]",
            "rate": "30.4000",
            "min": "50",
            "max": "5000",
            "type": "default",
            "desc": "Cheapest price\r\nNo Refill\r\nLow drop pack",
            "dripfeed": "0"
            },
            {
            "service": "64",
            "name": "#1 Instagram Post Saves [Real] \ud83d\ude07 [No Drop]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "7.8000",
            "min": "100",
            "max": "5000",
            "type": "default",
            "desc": "\ud83d\ude07 Mostly Instant Start\r\n\ud83d\ude07 Required Post Link\r\n\ud83d\ude07 Stable, Always Working\r\n\ud83d\ude07 Fast\r\n\r\nURL Format : https:\/\/www.instagram.com\/p\/CP8BvSOBJ5j\/",
            "dripfeed": "0"
            },
            {
            "service": "70",
            "name": "#2 Telegram Group Members [Worldwide] \ud83d\ude07 (Super Cheapest)",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "58.5000",
            "min": "1000",
            "max": "5000",
            "type": "default",
            "desc": "\ud83d\udc49 0-6h Start\r\n\ud83d\udc49 100-200\/day\r\n\ud83d\udc49 30-50% may Drop\r\n\ud83d\udc49 No refill\r\n\ud83d\udc49 Worldwide",
            "dripfeed": "0"
            },
            {
            "service": "118",
            "name": "Instagram Superfast Followers Auto Refill 30 days",
            "category": "\ud83d\udd35 AUTO REFILL INSTAGRAM FOLLOWERS",
            "rate": "64.6000",
            "min": "10",
            "max": "50000",
            "type": "default",
            "desc": "high quality followers\r\nauto refill 30 days\r\nsuper instant",
            "dripfeed": "0"
            },
            {
            "service": "119",
            "name": "Instagram Superfast Followers Auto Refill 60 days+Button Max 300K",
            "category": "\ud83d\udd35 AUTO REFILL INSTAGRAM FOLLOWERS",
            "rate": "69.1600",
            "min": "10",
            "max": "300000",
            "type": "default",
            "desc": "0-10Min Start\r\n10K+ Per Day\r\nHigh Quality\r\nCurrent Drop=0-3%\r\nAuto Refill 60Days",
            "dripfeed": "0"
            },
            {
            "service": "69",
            "name": "#1 Telegram Channel Subscribers [Worldwide] \ud83d\ude07 (Super Cheapest)",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "71.5000",
            "min": "1000",
            "max": "5000",
            "type": "default",
            "desc": "\ud83d\udc49 0-6h Start\r\n\ud83d\udc49 100-200\/day\r\n\ud83d\udc49 30-50% may Drop\r\n\ud83d\udc49 No refill\r\n\ud83d\udc49 Worldwide",
            "dripfeed": "0"
            },
            {
            "service": "120",
            "name": "Instagram Superfast Followers Auto Refill 90 days Max 200K |",
            "category": "\ud83d\udd35 AUTO REFILL INSTAGRAM FOLLOWERS",
            "rate": "74.4800",
            "min": "10",
            "max": "200000",
            "type": "default",
            "desc": "0-10Min Start\r\nSpeed 10k+ Per Day\r\nHigh Quality\r\nCurrent Drop:0%\r\nAuto Refill 90Days",
            "dripfeed": "0"
            },
            {
            "service": "72",
            "name": "#1 YouTube Video Likes [ Original ] \ud83d\ude0d [20-30k\/d] \u26a1 [ NR ]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "91.0000",
            "min": "20",
            "max": "95000",
            "type": "default",
            "desc": "\u2764 0-1h\r\n\u2764 20-30k\/d\r\n\u2764 5-20% drop\r\n\u2764 No refill\/ refund",
            "dripfeed": "0"
            },
            {
            "service": "73",
            "name": "#2 YouTube Video Likes [ INDIAN + Original ] \ud83d\ude0d [30 Day Guarantee] \u26a1 [ Less Drop ]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "102.7000",
            "min": "20",
            "max": "95000",
            "type": "default",
            "desc": "\u26a1 0-1h\r\n\u26a1 20-30k\/d\r\n\u26a1 Less drop\r\n\u26a1 R30",
            "dripfeed": "0"
            },
            {
            "service": "74",
            "name": "#4 YouTube Views [No Drop] \ud83d\ude0d [Lifetime Guarantee] \ud83e\udde1 [Super Cheapest]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "104.0000",
            "min": "500",
            "max": "10000000",
            "type": "default",
            "desc": "\ud83d\udd25 Cheapest in Whole Market\r\n\ud83d\udd25 Start: 0-12hrs\r\n\ud83d\udd25 Drop rate: Non Drop (0-5% when there is update)\r\n\ud83d\udd25 Non Refill\r\n\ud83d\udd25 0-1min retention\r\n\ud83d\udd25 Usually Lifetime Guarantee\r\n\ud83d\udd25 Speed: 300-500\/d",
            "dripfeed": "0"
            },
            {
            "service": "53",
            "name": "#1 Instagram Verified Comments [Blue Tick\u2714\ufe0f] \ud83e\udd29 [Original Account] \ud83e\udde1 [No Drop]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "130.0000",
            "min": "1",
            "max": "1",
            "type": "package",
            "desc": "\ud83e\udd29 Blue Tick\u2714\ufe0f Account\r\n\ud83e\udd29 Original Account\r\n\ud83e\udd29 No Drop\r\n\ud83e\udd29 Start Time 0 to 24hr\r\n\ud83e\udd29 Mostly Indian Account\r\n\r\n\ud83e\udd29 Contact For Bulk Comments",
            "dripfeed": "0"
            },
            {
            "service": "54",
            "name": "#2 Instagram Verified Comments [Blue Tick\u2714\ufe0f] \ud83e\udd29 [According To Yourself] \ud83e\udde1 [No Drop]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "143.0000",
            "min": "1",
            "max": "1",
            "type": "custom_comments_package",
            "desc": "\ud83e\udd29 Blue Tick\u2714\ufe0f Account\r\n\ud83e\udd29 Original Account\r\n\ud83e\udd29 No Drop\r\n\ud83e\udd29 Start Time 0 to 24hr\r\n\ud83e\udd29 Mostly Indian Account\r\n\ud83e\udd29 According To Yourself\r\n\r\n\ud83e\udd29 Contact For Bulk Comments",
            "dripfeed": "0"
            },
            {
            "service": "76",
            "name": "#2 YouTube Views [100% Safe] \ud83d\ude0d [USA] \ud83e\udde1 [Super Instant] \ud83e\udd29 [NO DROP]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "253.5000",
            "min": "1000",
            "max": "1000000",
            "type": "default",
            "desc": "\u26a1 100% Safe\r\n\u26a1 Targeted Country : USA\r\n\u26a1 NO DROP\r\n\u26a1 30 Days Refill\r\n\u26a1 INSTANT",
            "dripfeed": "0"
            },
            {
            "service": "77",
            "name": "#3 YouTube Views [100% Safe] \ud83d\ude0d [UK] \ud83e\udde1 [Super Instant] \ud83e\udd29 [NO DROP]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "253.5000",
            "min": "1000",
            "max": "1000000",
            "type": "default",
            "desc": "\u26a1 100% Safe\r\n\u26a1 Targeted Country : UK\r\n\u26a1 NO DROP\r\n\u26a1 30 Days Refill\r\n\u26a1 INSTANT",
            "dripfeed": "0"
            },
            {
            "service": "78",
            "name": "#5 YouTube Views [100% Safe] \ud83d\ude0d [CANADA] \ud83e\udde1 [Super Instant] \ud83e\udd29 [NO DROP]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "253.5000",
            "min": "1000",
            "max": "1000000",
            "type": "default",
            "desc": "\u26a1 100% Safe\r\n\u26a1 Targeted Country : CANADA\r\n\u26a1 NO DROP\r\n\u26a1 30 Days Refill\r\n\u26a1 INSTANT",
            "dripfeed": "0"
            },
            {
            "service": "79",
            "name": "#6 YouTube Views [100% Safe] \ud83d\ude0d [BRAZIL] \ud83e\udde1 [Super Instant] \ud83e\udd29 [NO DROP]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "253.5000",
            "min": "1000",
            "max": "1000000",
            "type": "default",
            "desc": "\u26a1 100% Safe\r\n\u26a1 Targeted Country : BRAZIL\r\n\u26a1 NO DROP\r\n\u26a1 30 Days Refill\r\n\u26a1 INSTANT",
            "dripfeed": "0"
            },
            {
            "service": "80",
            "name": "#7 YouTube Views [100% Safe] \ud83d\ude0d [RUSSIA] \ud83e\udde1 [Super Instant] \ud83e\udd29 [NO DROP]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "253.5000",
            "min": "1000",
            "max": "1000000",
            "type": "default",
            "desc": "\u26a1 100% Safe\r\n\u26a1 Targeted Country : RUSSIA\r\n\u26a1 NO DROP\r\n\u26a1 30 Days Refill\r\n\u26a1 INSTANT",
            "dripfeed": "0"
            },
            {
            "service": "65",
            "name": "#1 YouTube Subscribers [Cheap Service] \ud83d\ude07 [Usually Instant]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "258.7000",
            "min": "200",
            "max": "3000",
            "type": "default",
            "desc": "\ud83d\udc49 Instant\r\n\ud83d\udc49 Start: 12H\r\n\ud83d\udc49 1k\/D\r\n\ud83d\udc49 No refill\/refund in any case\r\n\ud83d\udc49 This service can drop in the next hour or the next day after status turns to complete.",
            "dripfeed": "0"
            },
            {
            "service": "75",
            "name": "#1 YouTube Views [100% Safe] \ud83d\ude0d [INDIAN] \ud83e\udde1 [Super Instant] \ud83e\udd29 [Lifetime Guaranteed]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "279.5000",
            "min": "1000",
            "max": "1000000",
            "type": "default",
            "desc": "\ud83d\udc95 Instant Start\r\n\ud83d\udc95 Lifetime Guaranteed\r\n\ud83d\udc95 60-80% Retention\r\n\ud83d\udc95 Speed - 30-100k\/Day\r\n\ud83d\udc95 Auto Refill\r\n\ud83d\udc95 INDIAN",
            "dripfeed": "0"
            },
            {
            "service": "66",
            "name": "#2 YouTube Subscribers [500\/d Speed] \ud83d\ude07 [Cheap Service]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "388.7000",
            "min": "50",
            "max": "3000",
            "type": "default",
            "desc": "\ud83d\udc49 0-1h start\r\n\ud83d\udc49 500\/d speed\r\n\ud83d\udc49 40-50% drop can happen\r\n\ud83d\udc49 No refill\/refund in any case",
            "dripfeed": "0"
            },
            {
            "service": "67",
            "name": "#3 YouTube Subscribers [2k\/hour] \ud83d\ude07 [Ghost Subscribers]",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "741.0000",
            "min": "50",
            "max": "10000",
            "type": "default",
            "desc": "\ud83d\udc49 0-1h Start\r\n\ud83d\udc49 2k\/hour\r\n\ud83d\udc49 BOTS may drop 100%\r\n\ud83d\udc49 No Refill\/Refund in any case\r\n\ud83d\udc49 Ghost Subscribers",
            "dripfeed": "0"
            },
            {
            "service": "68",
            "name": "#9 YouTube Subscribers [Ads Method] (5\/2.5k) |(10-20\/day) | Life Time Guarantee",
            "category": "\ud83d\udd35Cheapest price package ",
            "rate": "2405.0000",
            "min": "10",
            "max": "2000",
            "type": "default",
            "desc": "\ud83d\udc49 Life Time Guarantee\r\n\ud83d\udc49Channel should have 3+ Videos\r\n\ud83d\udc49All users before subscribing will watch your video for 2-3 minutes\r\n\ud83d\udc491% Drop\r\n\ud83d\udc49Real Subscribers\r\n\ud83d\udc49Speed is not fixed can be 1 or 20 per day. we can only cancel not speedup",
            "dripfeed": "0"
            },
            {
            "service": "158",
            "name": "\ud83c\udd95\ud83d\udc69\ud83c\udffb Instagram Likes \u2763 [Female] [Low Drop] No Refill \ud83d\udeab",
            "category": "\ud83d\udd35INSTAGRAM FEMALE SERVICE \ud83d\udc69\u200d\ud83e\uddb0\u2764\ufe0f",
            "rate": "10.0900",
            "min": "20",
            "max": "15000",
            "type": "default",
            "desc": "Mostly female\r\nLow drop\r\nNo Refill",
            "dripfeed": "0"
            },
            {
            "service": "157",
            "name": "\ud83c\udd95\ud83d\udc25 I\u034fN\u034fS\u034fT\u034fA\u034fG\u034fR\u034fA\u034fM\u034f ~ F\u034fO\u034fL\u034fL\u034fO\u034fW\u034fE\u034fR\u034f \u3010\u2022 NO GUARNTEE \u2022\u3011|| 100?MALE \ud83d\udc69\ud83c\udffb || \ud83d\udd3a MAX 5K ||",
            "category": "\ud83d\udd35INSTAGRAM FEMALE SERVICE \ud83d\udc69\u200d\ud83e\uddb0\u2764\ufe0f",
            "rate": "24.8100",
            "min": "50",
            "max": "5000",
            "type": "default",
            "desc": "\ud83e\uddb8\ud83c\udffb\u200d\u2640\ufe0f 100?MALE \ud83d\udc69\ud83c\udffb\r\n\ud83e\uddb8\ud83c\udffb\u200d\u2640\ufe0f LOW DROP ( NO GUARANTEE)\r\n\ud83e\uddb8\ud83c\udffb\u200d\u2640\ufe0f MAX 1000\r\n\ud83e\uddb8\ud83c\udffb\u200d\u2640\ufe0f INSTANT START \ud83d\udd25\r\n",
            "dripfeed": "1"
            },
            {
            "service": "156",
            "name": "\ud83c\udd95\ud83d\udc69\ud83c\udffb Instagram Followers [Female] No Refill \ud83d\udeab",
            "category": "\ud83d\udd35INSTAGRAM FEMALE SERVICE \ud83d\udc69\u200d\ud83e\uddb0\u2764\ufe0f",
            "rate": "25.4800",
            "min": "50",
            "max": "5000",
            "type": "default",
            "desc": "No Refill\r\nNo refund\r\n95?males",
            "dripfeed": "0"
            },
            {
            "service": "159",
            "name": "\ud83c\udd95\ud83d\udc69\ud83c\udffb Instagram Reel \ud83d\udcfd Likes \u2763 [Female Majority] [Non Drop]",
            "category": "\ud83d\udd35INSTAGRAM FEMALE SERVICE \ud83d\udc69\u200d\ud83e\uddb0\u2764\ufe0f",
            "rate": "30.9000",
            "min": "20",
            "max": "5000",
            "type": "default",
            "desc": "Non drop and mostly female",
            "dripfeed": "0"
            },
            {
            "service": "161",
            "name": "\ud83c\udd95\ud83d\udc69\ud83c\udffb Instagram Followers [Female Majority] R30 \u267b",
            "category": "\ud83d\udd35INSTAGRAM FEMALE SERVICE \ud83d\udc69\u200d\ud83e\uddb0\u2764\ufe0f",
            "rate": "100.1800",
            "min": "100",
            "max": "100000",
            "type": "default",
            "desc": "30 days Refill\r\n90% majority female followers",
            "dripfeed": "0"
            },
            {
            "service": "160",
            "name": "\ud83c\udd95\ud83d\udc69\ud83c\udffb Instagram Comments \ud83d\udce9 [Female] [Random] Non Drop",
            "category": "\ud83d\udd35INSTAGRAM FEMALE SERVICE \ud83d\udc69\u200d\ud83e\uddb0\u2764\ufe0f",
            "rate": "248.0500",
            "min": "25",
            "max": "10000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "98",
            "name": "Facebook Page Followers | Max 100k | Non Drop | Lifetime Guarantee |",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "16.7200",
            "min": "10",
            "max": "10000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "103",
            "name": "\ud83d\udc99 Facebook Post Likes | \ud83d\udc8eNon Drop | \u2705Completed In Day | \u26a1Speed: 1-5K Per Day | \ud83d\udd2510 Days Guarantee | \u2764SPECIAL\u2764",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "41.1500",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "96",
            "name": "\ud83c\udd95 Facebook Post Likes | \ud83d\udc4dLike React | \ud83d\udd25NON DROP | \ud83d\ude80 Speed:- 1k-5k\/Day | \u2705Start:- 0-3hrs | \u267b\ufe0f30 Days Guarantee",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "87.6700",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "104",
            "name": "\ud83d\udc99 Facebook Post Likes | \ud83d\udc8eNon Drop | \u2705Completed In 2 Days | \u26a1Speed: 1-5K Per Day | \ud83d\udd25 Lifetime Guarantee | \u2764SPECIAL\u2764",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "93.9400",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "102",
            "name": "\ud83d\udd35ID:379 Facebook Video Views [SPEED 500k NO REFILL]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "98.8000",
            "min": "500",
            "max": "100000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "105",
            "name": "\ud83d\udd35ID:355 Facebook Post Likes - [NO DROP + REAL + REFILL 30D + SPEED 100K]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "98.8000",
            "min": "100",
            "max": "5000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "106",
            "name": "\ud83d\udd35ID:360 Facebook Instant Post Reaction - [ANGRY] \ud83d\ude21",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "167.9600",
            "min": "20",
            "max": "2000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "107",
            "name": "\ud83d\udd35ID:368\ud83c\uddee\ud83c\uddf3Facebook Post Likes - [INDIA + HAHA] \ud83d\ude01",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "167.9600",
            "min": "50",
            "max": "1000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "108",
            "name": "\ud83d\udd35ID:366\ud83c\uddee\ud83c\uddf3Facebook Post Likes - [INDIA + LOVE] \u2764\ufe0f",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "167.9600",
            "min": "50",
            "max": "1000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "109",
            "name": "\ud83d\udd35ID:369\ud83c\uddee\ud83c\uddf3Facebook Post Likes - [INDIA + WOW] \ud83d\ude2e",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "167.9600",
            "min": "50",
            "max": "1000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "112",
            "name": "\ud83d\udd35ID:370\ud83c\uddee\ud83c\uddf3Facebook Post Likes - [INDIA + SAD] \ud83d\ude22",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "167.9600",
            "min": "50",
            "max": "1000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "99",
            "name": "Facebook Page Followers | Max 100k | Non Drop | Lifetime Guarantee |",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "193.0400",
            "min": "100",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "110",
            "name": "\ud83d\udd35ID:356 Facebook Post Likes [ REAL + NO DROP + REFILL LIFETIME]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "197.6000",
            "min": "50",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "111",
            "name": "\ud83d\udd35ID:365 \ud83c\uddee\ud83c\uddf3Facebook Post Likes - [ INDIAN + REAL + NO DROP]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "197.6000",
            "min": "50",
            "max": "100",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "113",
            "name": "\ud83d\udd35ID:371\ud83c\uddee\ud83c\uddf3Facebook Post Likes - [INDIA + CARE] \ud83e\udd70",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "197.6000",
            "min": "50",
            "max": "50",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "97",
            "name": "\ud83c\udd95\ud83c\udf53Non Drop Facebook Page Likes [0% Drop] \u26a1FAST\u26a1 VIP SERVER \ud83d\ude80Speed: 5k-20k\/Day \u2705Start:0-12hrs \ud83d\udc8eLifetime Guarantee",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "244.3100",
            "min": "100",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "114",
            "name": "\ud83d\udd35ID:351 Facebook Page Likes [ REAL + NO DROP + FOLLOWERS]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "247.0000",
            "min": "10",
            "max": "500000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "115",
            "name": "\ud83d\udd35ID:1535 Facebook Page Likes - [INDIAN +REAL + NO DROP]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "247.0000",
            "min": "100",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "100",
            "name": "\ud83c\uddee\ud83c\uddf3 Facebook Page Followers | INDIA | Max 5k | Non Drop | Lifetime Guarantee",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "272.0800",
            "min": "50",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "12",
            "name": "\ud83d\udc80Report Spam | \ud83d\udd35 Facebook Account | \ud83d\ude80Speed:- 1k+\/Day | \ud83d\udc8eLifetime Refill",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "279.1800",
            "min": "1000",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "116",
            "name": "\ud83d\udd35ID:344 Facebook Profile Followers [SPEED 10K\/D + NO DROP]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "296.4000",
            "min": "100",
            "max": "500000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "117",
            "name": "\ud83d\udd35ID:346 Facebook Profile Followers - [INDIAN +REAL + NO DROP]]",
            "category": "\ud83d\udd35FACEBOOK SERVICES",
            "rate": "296.4000",
            "min": "100",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "39",
            "name": "AMAZON PRIME \ud83d\udcfd\ufe0f 1 MONTH",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX \ud83c\udfa5",
            "rate": "40.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link \r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "134",
            "name": "\ud83c\udfeeYOUTUBE PREMIUM 1 MONTH INDIVIDUAL",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX \ud83c\udfa5",
            "rate": "47.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link \r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n",
            "dripfeed": "0"
            },
            {
            "service": "41",
            "name": "NETFLIX ACCOUNT 1 SCREEN \ud83c\udfa51 MONTH",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX \ud83c\udfa5",
            "rate": "100.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link \r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "124",
            "name": "\ud83d\udc41\ufe0f\u200d\ud83d\udde8\ufe0fSONYLIV 1 MONTH 1 SCREEN",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX \ud83c\udfa5",
            "rate": "100.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link\r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "42",
            "name": "AMAZON PRIME \ud83d\udcfd\ufe0f\u00a0\u00a06 MONTHS PACK",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX\ud83c\udfa5",
            "rate": "150.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link\r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "44",
            "name": "NETFLIX ACCOUNT \ud83c\udfa52 SCREEN (1 MONTH)",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX\ud83c\udfa5",
            "rate": "180.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link\r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "43",
            "name": "AMAZON PRIME ACCOUNT \ud83d\udcfd\ufe0f 1 YEAR",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX\ud83c\udfa5",
            "rate": "200.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link\r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "45",
            "name": "NETFLIX ACCOUNT\ud83c\udfa5 4 SCREEN\u00a0(1 MONTH)",
            "category": "\ud83d\udd35\ud83d\udc40PREMIUM ACCOUNTS \ud83d\udc40 AMAZON PRIME \ud83d\udcfd\ufe0f \/ NETFLIX\ud83c\udfa5",
            "rate": "250.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Add your email id or mobile number in the link\r\nID and PASSWORD will be sent within 30mins to 5 hours\r\nOnce ordered please contact us on whatsapp\r\n\r\n*THANK YOU* \ud83d\ude4f\ud83c\udffb\ud83e\udd1d",
            "dripfeed": "0"
            },
            {
            "service": "1",
            "name": "\ud83c\udd95\ud83c\udf39Non Drop Instagram Likes [0-3% Drop] BEST STABLE LIKES - Start:- Instant - \ud83c\udf39 BEST NON DROP SERVER [ \u267b\ufe0fRefill Button \u2705 ] \ud83d\udc8e Lifetime Guarantee",
            "category": "\ud83d\udd35 YouTube Services\u2764\ufe0f",
            "rate": "11.3400",
            "min": "20",
            "max": "50000",
            "type": "default",
            "desc": "\ud83c\udf39 OFFER \ud83c\udf39\r\n\ud83c\udf39 Special Server by ADMIN \ud83c\udf39\r\n\r\nStart:- 0-1 hr\r\nSpeed:- 5k per hour\r\nGuarantee:- Lifetime Guarantee\r\nDrop:- 0-3%\r\n\r\n\ud83c\udf39We Recommend this server if you want NON DROP STABLE Likes\ud83c\udf39",
            "dripfeed": "0"
            },
            {
            "service": "35",
            "name": "\ud83c\udd95\ud83c\udf53YouTube Suggested Views \u2705OWN FAST SERVER \u26a1 INSTANT\u26a1 \ud83d\udd25NO DROP\ud83d\udd25 \ud83d\ude80Speed:10k-70k\/Day \u2705Start: 0-2hrs \u267b\ufe0f Lifetime Guarantee \ud83c\udf53Must Try once \ud83d\udce3 CHEAPEST IN WORLD",
            "category": "\ud83d\udd35 YouTube Services\u2764\ufe0f",
            "rate": "86.6200",
            "min": "100",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "125",
            "name": "\ud83c\udd95\ud83c\udf53 Non Drop YouTube Views + Bonus Likes [0-2% Drop] \u26a1FAST\u26a1BEST STABLE VIEWS - \ud83d\ude80Start:- 0-8hrs - \ud83c\udf2a\ufe0fSpeed:- 2k-10k\/Day \u2705 BEST NON DROP SERVER - \ud83d\udc8e Lifetime Guarantee",
            "category": "\ud83d\udd35 YouTube Services\u2764\ufe0f",
            "rate": "89.4100",
            "min": "100",
            "max": "99990000",
            "type": "default",
            "desc": "Start:- 0-3 hr [ INSTANT ]\r\nSpeed:- 2k-10k per hour [ speed may be slow if more overloaded 1k+\/Day]\r\nGuarantee:- Lifetime Guarantee\r\nDrop:- 0-2%\r\n\r\n\r\n\ud83d\udcccYou get 3-10% Likes on video\r\n\ud83d\udccc30sec - 5min retention\r\n\ud83d\udcccSome time slow depends on Servers queue\r\n\r\n\u26a0\u26a0\u26a0NOTE\u26a0\u26a0\u26a0\r\n\r\n\ud83d\udd38Don't use streamed video we not give guarantee of refill on those orders .\r\n\ud83d\udd38https:\/\/www.youtube.com\/watch?v=3p7nXl1uj \u274cDon't use links like this             this\r\n\ud83d\udd38 Refill possible after 10% Drop only ; No refill\/Refund if views down from start count \/ No Refund if link is wrong\r\n\ud83d\udd38No partial\/Cancel after placing order\r\n\r\n\ud83c\udf39We Recommend this server if  you want NON DROP STABLE Views",
            "dripfeed": "0"
            },
            {
            "service": "38",
            "name": "\u2b55\ud83c\udd95 YouTube Watchtime | \ud83c\udf1f CHEAPEST IN MARKET | \u231a Video Length: 15-45min |\ud83d\udd25R30 | \ud83d\ude80 INSTANT | \u274cCancel Button Enabled",
            "category": "\ud83d\udd35 YouTube Services\u2764\ufe0f",
            "rate": "497.0000",
            "min": "100",
            "max": "10000",
            "type": "default",
            "desc": "\u00d7\r\n\ud83c\udf53CHEAPEST WATCHTIME\r\n\r\n\ud83d\udd25Start: INSTANT - 6 hrs\r\n\ud83d\udd25Speed: Natural [100-500\/day]\r\n\ud83d\udd25Guarantee: 30 Days Trusted Guarantee\r\n\r\n\ud83d\udd25No Drop\r\n\r\n\u2b50Video Length must be 15-45min only\r\n\r\n\ud83c\udfafUsually its Good server but if drop we provide 30 Days Guarantee\r\n[ In this server you get 30-50% results according to quantity]\r\n\r\n\u274cCANCEL BUTTON ENABLED\u274c\r\n",
            "dripfeed": "0"
            },
            {
            "service": "36",
            "name": "\ud83d\udce3\ud83c\udd95 YouTube WatchTime \ud83d\udd25100% NON DROP \ud83c\udfafSource:- HOMEPAGE \ud83d\udcccVideo Length 60min+ \ud83d\ude80Speed:- 500-1k\/Day \u2705Start:- 0-6hrs \ud83d\udc8e Lifetime Guarantee\ud83d\udce2\ud835\ude3d\ud835\ude40\ud835\ude4e\ud835\ude4f \ud835\ude41\ud835\ude4a\ud835\ude4d\ud835\ude48\ud835\ude4a\ud835\ude49\ud835\ude44\ud835\ude4f\ud835\ude44\ud835\ude55\ud835\ude3c\ud835\ude4f\ud835\ude44\ud835\ude4a\ud835\ude49",
            "category": "\ud83d\udd35 YouTube Services\u2764\ufe0f",
            "rate": "576.5100",
            "min": "200",
            "max": "4000",
            "type": "default",
            "desc": "\ud83c\udf81One of the kind Watchtime with HOMEPAGE source\r\n\ud83d\udd17 Link = Put Video link[60min+]\r\n\r\n\u2705Start:- 0-6hrs [\u26a1Fast Start]\r\n\u26a1Speed:- 500-1k per day\r\n\ud83d\udc8eGuarantee:-Lifetime\r\n\ud83d\udd25Drop:- 0%\r\n\u231aVideo Length :- 60min+\r\n\ud83d\udccaSource:- HOMEPAGE [Your video will be opened by searching from YOUTUBE HOME PAGE ]\r\n\r\n\u2b50CHANCES TO GET YOUR VIDEO IN RANKING VIDEOS\r\n\u2b50REAL ORGANIC TRAFFIC VIEWS ONLY !!\r\n\r\n\ud83d\udce2 \ud835\ude3d\ud835\ude40\ud835\ude4e\ud835\ude4f\ud835\ude41\ud835\ude4a\ud835\ude4d\ud835\ude48\ud835\ude4a\ud835\ude49\ud835\ude44\ud835\ude4f\ud835\ude44\ud835\ude55\ud835\ude3c\ud835\ude4f\ud835\ude44\ud835\ude4a\ud835\ude49\r\n[This service helps your channel to get monitzed fast]\r\n\r\n\ud83d\udce3Note\r\n\r\n\ud83d\udccc Video should be Embedded ; if not then it delays\r\n\ud83d\udccc Put Video link in link box ; video must be 60min+\r\n\ud83d\udccc Once order placed we can't cancel\/Partial in any terms\r\n\ud83d\udccc If you Deleted the videos ; order should be considered as completed\r\n\ud83d\udcccDon't order duplicate on same link while running this order\r\n\r\n",
            "dripfeed": "0"
            },
            {
            "service": "37",
            "name": "\ud83d\udce3\ud83c\udd95 YouTube WatchTime\u00a0\u23f0ANY LENGTH\u00a0\ud83d\udd25 NON DROP \ud83c\udfafSource:- MIX [ Homepage+Suggested+Search ] \ud83d\udccc All Video Length \ud83d\ude80Speed:- 500-1k\/Day \u2705Start:- 0-30hrs \ud83d\udc8e Lifetime Guarantee \ud83d\udce2 \ud835\ude3d\ud835\ude40\ud835\ude4e\ud835\ude4f n\ud835\ude41\ud835\ude4a\ud835\ude4d \ud835\ude48\ud835\ude4a\ud835\ude49\ud835\ude44\ud835\ude4f\ud835\ude44\ud835\ude55\ud835\ude3c\ud835\ude4f\ud835\ude44\ud835\ude4a\ud835\ude49",
            "category": "\ud83d\udd35 YouTube Services\u2764\ufe0f",
            "rate": "781.6500",
            "min": "500",
            "max": "10000",
            "type": "default",
            "desc": "\ud83c\udf81One of the kind Watchtime with MIX source\r\n\ud83d\udd17 Link = Put Channel Link\r\n\r\n\u2705Start:- 0-48hrs\r\n\u26a1Speed:- 500-1k per day\r\n\ud83d\udc8eGuarantee:- Lifetime\r\n\ud83d\udd25Drop:- 0%\r\n\u231aVideo Length :- Any Length\r\n\ud83d\udccaSource:- HOMEPAGE + SUGGESTED + SEARCH\r\n\r\n\ud83d\udce2 \ud835\ude3d\ud835\ude40\ud835\ude4e\ud835\ude4f \ud835\ude41\ud835\ude4a\ud835\ude4d \ud835\ude48\ud835\ude4a\ud835\ude49\ud835\ude44\ud835\ude4f\ud835\ude44\ud835\ude55\ud835\ude3c\ud835\ude4f\ud835\ude44\ud835\ude4a\ud835\ude49\r\n[This service helps your channel to get monitzed fast]\r\n\r\n\u2b50CHANCES TO GET YOUR VIDEO IN RANKING VIDEOS\r\n\u2b50REAL ORGANIC TRAFFIC VIEWS ONLY !!\r\n\r\n\ud83d\udce3Note\r\n\r\n\ud83d\udccc Video should be Embedded ; if not then it delays\r\n\ud83d\udccc Put Channel Link in link box ; To get best results put channel link with 5-6 videos\r\n\ud83d\udccc Once order placed we can't cancel\/Partial in any terms\r\n\ud83d\udccc If you Deleted the videos ; order should be considered as completed\r\n\ud83d\udcccDon't order duplicate on same link while running this order\r\n",
            "dripfeed": "0"
            },
            {
            "service": "216",
            "name": "Youtube Likes | Real | Max 100K | Low Drop | 10k\/Day | No Refill |",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "53.2000",
            "min": "100",
            "max": "100000",
            "type": "default",
            "desc": "Start: 0-2H\r\nSpeed: 1k\/Day\r\nDrop rate : Low\r\nRefill: No Guarantee\/ No Refill\r\nQuality: Avarage\r\nAverage: 2 hour",
            "dripfeed": "0"
            },
            {
            "service": "215",
            "name": "Youtube Likes | Max 100K | 50k\/Hour | NON DROP | Lifetime Guarantee |",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "92.7200",
            "min": "50",
            "max": "100000",
            "type": "default",
            "desc": "Start: 0-2H\r\nSpeed: 5k\/Day\r\nRefill: Lifetime\r\nQuality: Real\r\nAverage: 5 hour\r\n\ud83d\udca2Drop Rate: 0-15%",
            "dripfeed": "0"
            },
            {
            "service": "151",
            "name": "\u25b6\ufe0f Youtube Watchtime [+\ud835\udfcf\ud835\udfce \ud835\udc26\ud835\udc22\ud835\udc27\ud835\udc2c Video] [\ud835\udfcf\ud835\udfce\ud835\udfce% NON DROP] [\ud835\udc12\ud835\udc0e\ud835\udc14\ud835\udc11\ud835\udc02\ud835\udc04 - Natural Suggested] \ud83d\udd25",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "194.9700",
            "min": "500",
            "max": "20000",
            "type": "default",
            "desc": "Link: https:\/\/www.youtube.com\/watch?v=TJaA5Q7MiAE\r\nStart: 0-1H\r\nSpeed: 50-100+\r\nQuality: NATURAL SUGGESTED VIEWS | RECOMMENDED\r\nRefill: NON DROP\r\nAverage: Not Enough Data\r\n\r\n>The system does not have its own counter, so it only relies on the number of views starting and ending on the video to calculate views. In the process of running views, if the video gets natural views mixed with our views then we will not be responsible.\r\n\r\n\ud83d\udd25SOURCE - NATURAL SUGGESTED VIEWS\r\n\ud83d\udd25100% NON DROP ONLY !!\r\n\ud83d\udd2510 Mins + Video ONLY !!\r\n\ud83d\udd25Use videos longer than 10 minutes for the best effect.\r\n\ud83d\udd2530 DAYS REFILL IF ANY DROP (But No Drops at all)\r\n============================================\r\n\ud83d\udd251000 VIEWS = 160+ HOURS ONLY\r\n============================================\r\n\ud83d\udd25Time Completion time 1000 hours.\r\n- Enter 6300 Views to Complete 1000 Hours\r\n- Example: Using 8 videos in the same channel. Each video orders more than 2000 views. It only takes 4 days to complete 4000 hours.\r\n\r\n>NOTE -\r\n- Do not order multiple titles for one video at the same time.\r\n- This Service Never DROPS , All Views are ORGANIC ONLY always ! So please dont ask for refills normally !\r\n- After Completion it takes upto 1Hr - 72Hrs to completely show in YOUTUBE STUDIO !!",
            "dripfeed": "0"
            },
            {
            "service": "213",
            "name": "YouTube Watchtime | Put Video 15 min+ | Non Drop | Lifetime Refill | 500-1000\/day |",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "224.9600",
            "min": "300",
            "max": "10000",
            "type": "default",
            "desc": "\u2714\ufe0f Quantity 1000 = 250 Hours\r\n\r\nStart: 0-1H\r\nSpeed: 500-1000 Hours\/Day\r\nRefill: Lifetime\r\nQuality: Real\r\nDrop: 1%\r\n\r\n\u2714 Video length must be 15 Min +\r\n\u2714 If you put video private or removed no refill \/ refund\r\n\u2714 If You Order 1000 Views, You Will Get 250 Hours\r\n\r\n\u267b For refill, please send us the video analytics screenshot from desktop from order date to current date.",
            "dripfeed": "0"
            },
            {
            "service": "217",
            "name": "Youtube Subscriber | 100% INDIAN Real Users | No Refill | Max 5k | Instant Start |",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "262.9600",
            "min": "100",
            "max": "5000",
            "type": "default",
            "desc": "\r\nStart: 0-1H\r\nSpeed: 1k\/day\r\nDrop rate : full drop can bee seen\r\nRefill: No Guarantee \/ No refill\r\nQuality: 100% Real Indian Users",
            "dripfeed": "0"
            },
            {
            "service": "214",
            "name": "Youtube Watchtime | 4k Watchtime | Non Drop | Lifetime Refill | Real | Put 1 Hour+ Video |",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "570.7600",
            "min": "500",
            "max": "4000",
            "type": "default",
            "desc": "Start: 0-6H\r\nSpeed: 300- 600 Hour\/Day\r\nRefill: Lifetime\r\nQuality: Real\r\nDrop: 0-1%\r\n\r\n\u2705Put 60 Minutes+ Video\r\n\u2705 If you use videos longer than 1 hour : 1000 views = 1000+ hours of viewing",
            "dripfeed": "0"
            },
            {
            "service": "218",
            "name": "Youtube Subscribers | NON DROP | 500\/Day | Max 1k | Lifetime Guarantee | Best For Monitization |\ud83d\udd25",
            "category": "\ud83d\udcb2YouTube : Revenue [100% Safe & Real]",
            "rate": "2603.0000",
            "min": "1000",
            "max": "1000",
            "type": "default",
            "desc": "Start: 0-24hrs\r\nSpeed: 1k\/Day\r\nRefill: Lifetime\r\nQuality: Real\r\nDrop: 0-10%\r\n\r\nPut Channel Link Only\r\n\ud83d\udd25Best Package for monitization",
            "dripfeed": "0"
            },
            {
            "service": "2",
            "name": "\ud83d\udce3\ud83c\udd95\ud83c\uddee\ud83c\uddf3 Indian Looking Followers | \ud83d\ude80Speed:- 500+\/hr | \u27050-15min Start | \u267b\ufe0f 15 Days Guarantee | \ud83c\udf53STABLE",
            "category": "\ud83d\udd35\ud83c\uddee\ud83c\uddf3 TOP INDIAN SERVICE SPECIAL",
            "rate": "98.7200",
            "min": "50",
            "max": "10000",
            "type": "default",
            "desc": "\u26a1 In Link Put profile link of profile only\r\n*****************************\r\n\u2728Speed : 1000-5000\/Day\r\n\ud83c\udf00 Refill Guarantee : 15 Days\r\n\u231a Start :0 - 2hrs\r\n\ud83d\udc8e Quality : Awesome\r\n\ud83d\udca6Drop : Stable ] \ud83d\udd25NON\/LESS DROP\ud83d\udd25\r\n\r\n\r\n\ud83d\udc8e VIP LEVEL users can ask for custom rates in this service\r\n\ud83d\udd25API\/VIP users can ask for Discount in this service\r\n\ud83c\udf53Big Resellers also welcome for Discounts.\r\n\r\n\u203c\ufe0f APIs fetch this service in your panel \u203c\ufe0f",
            "dripfeed": "0"
            },
            {
            "service": "7",
            "name": "\ud83c\uddee\ud83c\uddf3 Instagram Custom Comments |\ud83d\udd25NON DROP | \ud83c\uddee\ud83c\uddf3INDIAN MIX | \ud83d\ude80 INSTANT+ ULTRA FAST | \ud83d\udc8e Lifetime Guarantee | \ud83d\udd3aMax:- 1k | \ud83c\uddee\ud83c\uddf3 INDIAN SPECIAL",
            "category": "\ud83d\udd35\ud83c\uddee\ud83c\uddf3 TOP INDIAN SERVICE SPECIAL",
            "rate": "324.8300",
            "min": "5",
            "max": "1000",
            "type": "custom_comments",
            "desc": "\ud83d\udd25INDIAN EXCLUSIVE\ud83d\udd25\r\n\r\n\ud83d\ude0dStart:- 0-3hrs\r\n\ud83d\ude0dSpeed:- 500+ per Day\r\n\ud83d\ude0d Guarantee:- Lifetime\r\n\ud83d\ude0d Quality:- Best in Market\r\n\r\n\ud83c\uddee\ud83c\uddf3 INDIAN MIX HIGHLY\r\n\r\n\ud83c\udf53 Giving Supply of this Service\r\n\ud83c\udf53Asap Fetch in your Panel\r\n\ud83c\udf53 bWelcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "8",
            "name": "\ud83c\uddee\ud83c\uddf3\u2b55 YouTube Random Comments | \ud83c\udf1f HIGH SPEED | \ud83d\udd25 NON DROP | \ud83d\ude80 Speed:- 20k-80k\/Day | \ud83d\udc8e Lifetime Guarantee | \ud83d\udd3aMax:- 100k | \ud83d\udce2 Especially for Big Orders | \ud83c\uddee\ud83c\uddf3 INDIAN SPECIAL",
            "category": "\ud83d\udd35\ud83c\uddee\ud83c\uddf3 TOP INDIAN SERVICE SPECIAL",
            "rate": "770.6000",
            "min": "100",
            "max": "100000",
            "type": "default",
            "desc": "\ud83d\udd25INDIAN EXCLUSIVE\ud83d\udd25\r\n\ud83c\udf53 RANDOM \ud83c\udf53\r\n\r\n\ud83d\ude0dStart:- 0-12hrs\r\n\ud83d\ude0dSpeed:- 20k+ per Day\r\n\ud83d\ude0d Guarantee:- Lifetime\r\n\ud83d\ude0d Quality:- Best in Market\r\n\r\n\ud83d\udd25NON DROP \ud83d\udd25\r\n\r\n\ud83c\udf53 Giving Supply of this Service\r\n\ud83c\udf53Asap Fetch in your Panel\r\n\ud83c\udf53 Welcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "9",
            "name": "\ud83c\uddee\ud83c\uddf3\u2b55 YouTube Custom Comments | \ud83c\udf1f HIGH SPEED | \ud83d\udd25 NON DROP | \ud83d\ude80 Speed:- 20k-80k\/Day | \ud83d\udc8e Lifetime Guarantee | \ud83d\udd3aMax:- 500k | \ud83d\udce2 Especially for Big Orders | \ud83c\uddee\ud83c\uddf3 INDIAN SPECIAL",
            "category": "\ud83d\udd35\ud83c\uddee\ud83c\uddf3 TOP INDIAN SERVICE SPECIAL",
            "rate": "770.6000",
            "min": "100",
            "max": "500000",
            "type": "custom_comments",
            "desc": "\ud83d\udd25INDIAN EXCLUSIVE\ud83d\udd25\r\n\ud83c\udf53 CUSTOM \ud83c\udf53\r\n\r\n\ud83d\ude0dStart:- 0-12hrs\r\n\ud83d\ude0dSpeed:- 20k+ per Day\r\n\ud83d\ude0d Guarantee:- Lifetime\r\n\ud83d\ude0d Quality:- Best in Market\r\n\r\n\ud83d\udd25NON DROP \ud83d\udd25\r\n\r\n\ud83c\udf53 Giving Supply of this Service\r\n\ud83c\udf53Asap Fetch in your Panel\r\n\ud83c\udf53 Welcome for Discounts",
            "dripfeed": "0"
            },
            
            
            {
            "service": "13",
            "name": "\ud83c\udf8a Instagram REAL likes - \ud83d\ude80Speed:1K \/hr \ud83d\ude85Instant start \ud83d\udd25Drop: 5-10% [NR] \ud83d\ude09Extra Delivery Guaranteed\u2b50LIMITED OFFER",
            "category": "\ud83c\udf53 LIMITED OFFER",
            "rate": "6.5400",
            "min": "10",
            "max": "5000",
            "type": "default",
            "desc": "\ud83c\udfaf Quantity must be multiple of \ud83d\udcaf.\r\n\r\n\r\n\ud83d\udcab LIMITED TIME OFFER  \ud83d\udcab\r\n\ud83c\udf53FOR ALL USERS\ud83c\udf53\r\n\r\n\ud83d\ude80INSTANT START\r\n\ud83d\ude85Speed:  Fast\r\n\ud83d\udc80Drop:5-20% currently[But its NO Refill Service.]\r\n\ud83c\udf0eCountry: Worldwide\r\n\u2b50Drip feed enabled\r\n\r\nMay be less delivery\r\n\r\n\r\n\ud83c\udf53Giving supply of this service\r\n\ud83c\udf53APIs can add & resell this service",
            "dripfeed": "0"
            },
            {
            "service": "17",
            "name": "\ud83c\udf53\u2764Instagram Likes Real (High Quality) (Speed:10k\/day) \ud83d\udc8eNON DROP \ud83d\ude80INSTANT\ud83d\udd25Lifetime Guarantee",
            "category": "\ud83c\udf53 LIMITED OFFER",
            "rate": "13.1300",
            "min": "10",
            "max": "50000",
            "type": "default",
            "desc": "\ud83d\udc8eBest Server in whole Market\r\n\r\n\u2b50Start: INSTANT - 3hrs\r\n\u2b50Speed: 1-2k per hr\r\n\u2b50Quality: Real\r\n\u2b50Guarantee: LIFETIME\r\n\ud83d\udd25\ud83d\udc4cNON DROP\ud83d\udc4c\ud83d\udd25\r\n\r\n\ud83c\udf53Giving Supply of this service\r\n\ud83c\udf53Fetch asap in your panel\r\n\r\n\ud83d\udc8eELITE LEVEL users can ask for custom rates\r\n\ud83d\udd25API\/VIP users can ask for discount in this service\r\n\r\n\ud83c\udfafAfter order 15k, you can re-order upto 40k (15, 15k, 10k)",
            "dripfeed": "0"
            },
            {
            "service": "14",
            "name": "\ud83c\udd95\ud83c\udf53Instagram Likes [Speed: 500-2K\/H - 10K\/D] [REAL - \ud83c\udf53LOW DROP] \u2b50 - \ud83d\ude0dCheapest",
            "category": "\ud83c\udf53 LIMITED OFFER",
            "rate": "18.2800",
            "min": "10",
            "max": "10000",
            "type": "default",
            "desc": "\ud83d\udcab LIMITED OFFER \ud83d\udcab\r\n\ud83c\udf53FOR ALL USERS\ud83c\udf53\r\n\r\n\ud83d\udd25Start: INSTANT-1hr\r\n\ud83d\udd25Speed: 700-2k per hour\r\n\ud83d\udd25LOW DROP\r\n\r\n\ud83d\udc8eCheapest & Stable like in very low price\r\nNo panel can give 90% stable likes in this price",
            "dripfeed": "0"
            },
            {
            "service": "18",
            "name": "\ud83c\udf8a You tube Views [ Max 1M | Speed 5k\/day ] [ No Refill ] [ No Guarantee ] 0-12hr Start \u2b50LIMITED OFFER\u2b50",
            "category": "\ud83c\udf53 LIMITED OFFER",
            "rate": "32.7500",
            "min": "2500",
            "max": "1000000",
            "type": "default",
            "desc": "\ud83d\udcab LIMITED TIME OFFER \ud83d\udcab\r\n\ud83c\udf53FOR ALL USERS\ud83c\udf53\r\n\r\nGuarantee: No Refill if Drop !!No Gurantee of Delivery also !!\r\nStart time :1hr to 24 h\r\nSpeed Natural sometime fast\r\nNo Refill\r\nNO START COUNT\r\nEnter Full Video Link\r\nie: https:\/\/www.youtube.com\/link\r\n\r\nNO TICKET ALLOWED\r\nNO SUPPORT\r\nNO CANCEL\r\nNO REFUND\r\nNO REFILL\r\nNO GUARANTEE",
            "dripfeed": "0"
            },
            {
            "service": "16",
            "name": "\ud83c\udf53 Instagram Super Fast Followers | \ud83d\ude80FASTEST- \ud83d\udd2535D Refill\ud83d\udd25 [ Max:50k] [ \ud83d\ude80Speed:- 2k-3k\/hr ] [\ud83d\udd25 STABLE\ud83d\udd25 ]",
            "category": "\ud83c\udf53 LIMITED OFFER",
            "rate": "76.9200",
            "min": "100",
            "max": "5000",
            "type": "default",
            "desc": "\ud83d\udcab LIMITED TIME OFFER \ud83d\udcab\r\n\ud83c\udf53FOR ALL USERS\ud83c\udf53\r\n\r\n\u2757Start:- INSTANT\r\n\u2757Speed:- 2k-3k per hour [Speed like thunder\ud83c\udf2a\ufe0f]\r\n\u2757Drop:- 0-20% [\ud83d\udc8eSTABLE]\r\n\u2757Guarantee:- 35 Days Trusted Guarantee\ud83d\udd25\r\n\r\n\ud83d\udcafREFILL BUTTON ENABLED \ud83d\udcaf\r\n\r\n\ud83c\udf53Giving Supply of this Service\r\n\ud83c\udf53Asap Fetch in your panel\r\n\ud83c\udf53Welcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "15",
            "name": "\ud83c\udf8a YouTube Super Fast Likes [Max-100K] [\ud83d\ude80Speed:6k-15k\/day]\ud83d\udd25NON DROP - \ud83d\udc8e Lifetime Guarantee",
            "category": "\ud83c\udf53 LIMITED OFFER",
            "rate": "135.3700",
            "min": "50",
            "max": "100000",
            "type": "default",
            "desc": "\ud83d\udcab LIMITED TIME OFFER \ud83d\udcab\r\n\ud83c\udf53FOR ALL USERS\ud83c\udf53\r\n\r\n\u2757Start:- INSTANT- 3hrs\r\n\u2757Speed:- 10k-15k per Day\r\n\u2757Drop:-\ud83d\udd25NON DROP \ud83d\udd25\r\n\u2757 Guarantee:- 30 Days Guarantee \ud83d\udd25\r\n\r\n\ud83d\udcafREFILL BUTTON ENABLED\ud83d\udcaf\r\n\r\n\r\n\ud83c\udf53 Giving Supply of this Service\r\n\ud83c\udf53Fetch asap in your panel\r\n\ud83c\udf53No Discounts to any one\r\n\ud83c\udf53Cheapest & Best Server",
            "dripfeed": "0"
            },
            {
            "service": "202",
            "name": "Telegram Post Views Max 1M",
            "category": "\ud83d\udd18 Telegram - Post Views",
            "rate": "3.0400",
            "min": "50",
            "max": "1000000",
            "type": "default",
            "desc": "0-30Min Start\r\nSpeed:10k\/Hr",
            "dripfeed": "0"
            },
            {
            "service": "201",
            "name": "Telegram Public Group Members | Real Mixed | Max 10k | No Refill |",
            "category": "\ud83d\udd18 Telegram Members [ NO REFILL ]",
            "rate": "57.0000",
            "min": "10",
            "max": "30000",
            "type": "default",
            "desc": "Start: 0-1H\r\nSpeed: 1k-10k\/Day\r\nRefill: No\r\nQuality: Real\r\nAverage: 1 hour\r\n\r\n\ud83d\udca2Drop Rate: Low Drop\r\n\ud83d\udcccMake Sure The Group Public Before Order.\r\n\ud83d\udcccNo hacking, cracking, porn, gambling channel accepted",
            "dripfeed": "0"
            },
            {
            "service": "200",
            "name": "Telegram Public Group Members | Real | Max 100k | No Refill |",
            "category": "\ud83d\udd18 Telegram Members [ NO REFILL ]",
            "rate": "59.2800",
            "min": "10",
            "max": "10000",
            "type": "default",
            "desc": "Start: 0-1H\r\nSpeed: 1k-10k\/Day\r\nRefill: No\r\nQuality: Real\r\nAverage: 1 hour\r\n\r\n\ud83d\udca2Drop Rate: Low Drop\r\n\ud83d\udcccMake Sure The Group Public Before Order.\r\n\ud83d\udcccNo hacking, cracking, porn, gambling channel accepted",
            "dripfeed": "0"
            },
            {
            "service": "199",
            "name": "\ud83c\uddee\ud83c\uddf3Telegram Public Channel Members | INDIAN | Max 10K | No Refill |",
            "category": "\ud83d\udd18 Telegram Members [ NO REFILL ]",
            "rate": "136.0400",
            "min": "10",
            "max": "35000",
            "type": "default",
            "desc": "Start: 0-1H\r\nSpeed: 2k-10k\/Day\r\nRefill: No\r\nQuality: 100% Indian Subscriber\r\nAverage: 10 hour\r\n\r\n\ud83d\udca2Drop Rate: Low-mid,but can be high\r\n\ud83d\udcccThis Service Works on Private & public both channel\r\n\ud83d\udcccNo hacking, cracking, porn, gambling channel accepted",
            "dripfeed": "0"
            },
            {
            "service": "196",
            "name": "Telegram Public Channel Members | Max 15k | 15k\/Day | Instant |",
            "category": "\ud83d\udd18 Telegram Members [ NON DROP ]",
            "rate": "37.2400",
            "min": "10",
            "max": "15000",
            "type": "default",
            "desc": "Start: 0-6H\r\nSpeed: 10k\/Day\r\nRefill: No\r\nQuality: Real\r\nDrop: Low",
            "dripfeed": "0"
            },
            {
            "service": "197",
            "name": "Telegram Public Channel Members | Real | Max 10k | 0-5% Drop |",
            "category": "\ud83d\udd18 Telegram Members [ NON DROP ]",
            "rate": "68.4000",
            "min": "50",
            "max": "12000",
            "type": "default",
            "desc": "Start: 0-1H\r\nSpeed: 10k\/Day\r\nRefill: No\r\nQuality: good\r\nDrop: 0-5%",
            "dripfeed": "0"
            },
            {
            "service": "210",
            "name": "\u2709\ufe0fTelegram Mixed Members Max 35k No Drop",
            "category": "\ud83d\udd18 Telegram Members [ NON DROP ]",
            "rate": "75.2400",
            "min": "30",
            "max": "77777",
            "type": "default",
            "desc": "0-1hr Start\r\n30k\/Day\r\nNo Drop\r\nQuality Mix",
            "dripfeed": "0"
            },
            {
            "service": "198",
            "name": "\ud83c\uddee\ud83c\uddf3Telegram Members | INDIAN | NON DROP | 10K\/Day | Instant |",
            "category": "\ud83d\udd18 Telegram Members [ NON DROP ]",
            "rate": "147.4400",
            "min": "10",
            "max": "35000",
            "type": "default",
            "desc": "Start: 0-6H\r\nSpeed: 10k\/Day\r\nGuarantee : 30 days\r\nQuality: 100% real Indian Users\r\n\r\n\ud83d\udca2No refill If You Have Old Drops",
            "dripfeed": "0"
            },
            {
            "service": "133",
            "name": "\ud83c\uddee\ud83c\uddf3INSTAGRAM INDIAN FOLLOWERS INSTANT!! \ud83d\udd25- LIFETIME GUARANTEE - OFFER",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Indian Followers [ NON DROP ]",
            "rate": "64.9100",
            "min": "25",
            "max": "500000",
            "type": "default",
            "desc": "DESCRIPTION\r\nStart: 0-1H\r\nSpeed: 15K+\/Day\r\nQuality: REAL + INDIAN USERS MIX ACCOUNTS\r\nRefill: NON DROP\r\nAverage: Not Enough Data\r\n\r\n\ud83d\udd25ABOUT SERVICE -\r\n>100% NON DROP\r\n>HIGH QUALITY INDIAN MIX FOLLOWERS\r\n>LIFETIME GUARANTEE !!\r\n\r\nNOTE -PRICE MAY RAISE OR FALL AS PER DOLLAR RATE AND INSTAGRAM UPDATE\r\nLIFETIME REFILL ONLY FOR FOLLOWERS PURCHASED IN THIS SERVICE , WE DONT REFILL FOR OTHER SERVICE FOLLOWERS!! WE WILL CHECK ALL ORDERS BEFORE REFILLING !!",
            "dripfeed": "1"
            },
            {
            "service": "20",
            "name": "\ud83c\udf53 \ud83c\uddee\ud83c\uddf3 Instagram Followers [\ud83d\ude0dIndian Mix] \ud83d\udc8eLifetime Guarantee \ud83d\ude80Speed:- 15k\/day \ud83d\udce2Start: INSTANT \ud83d\udd25NON DROP -\ud83c\udfaf Highly Recommended",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Indian Followers [ NON DROP ]",
            "rate": "65.9200",
            "min": "10",
            "max": "1000000",
            "type": "default",
            "desc": "\ud83c\udf53BEST\ud83c\udf53QUALITY\ud83c\udf53NON DROP\r\n\r\n\ud83d\ude0dMostly INDIAN Followers\r\n\r\n\ud83d\udd25Start: INSTANT to 5 hrs\r\n\ud83d\udd25Speed: 5k-15k per day\r\n\ud83d\udd25Guarantee: \ud83d\udc8eLifetime Guaranteed\r\n\r\n\ud83d\ude0dNON DROP\ud83d\ude0d\r\n[0-10% rarely]\r\n\r\n\ud83d\udcafREFILL BUTTON ENABLED\ud83d\udcaf\r\n\r\n\ud83c\udfafRecommended by ADMIN\r\n\r\n\ud83c\udf53Giving Supply of this service\r\n\ud83c\udf53Asap Fetch in your panel\r\n\ud83c\udf53Welcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "222",
            "name": "INDIAN MIXED \ud835\udc14\ud835\udc25\ud835\udc2d\ud835\udc2b\ud835\udc1a \ud835\udc12\ud835\udc2d\ud835\udc1a\ud835\udc1b\ud835\udc25\ud835\udc1e |\u267b\ufe0f Refill \ud835\udfd1\ud835\udfd4\ud835\udfd3 Day |\u23e9 25-50K Per Day | \u25b6\ufe0f Instant",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Indian Followers [ NON DROP ]",
            "rate": "67.0200",
            "min": "10",
            "max": "1000000",
            "type": "default",
            "desc": "INDIAN MIXED \ud835\udc14\ud835\udc25\ud835\udc2d\ud835\udc2b\ud835\udc1a \ud835\udc12\ud835\udc2d\ud835\udc1a\ud835\udc1b\ud835\udc25\ud835\udc1e \u2611\ufe0f\r\n\u25b6\ufe0f FAST START\r\n\u267b\ufe0f Refill \ud835\udfd1\ud835\udfd4\ud835\udfd3 Day \r\n\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\u21dd\r\n\u25b6\ufe0f Start: 0 - 15 Min\r\n\ud83d\udca8 Speed: 25-50K \/ Day\r\n\ud83d\udd25 Quality: Real + Indian Mix\r\n\ud83d\udca7 Drop: Currently Non Drop\r\n\u267b\ufe0f Refil: 365 days\ud83d\ude31\ud83d\ude31\ud83d\ude31\r\nNo cancellation no refund once ordered\r\nIn worst case if drops Refill is still available \ud83d\ude0a\ud83d\udc4d",
            "dripfeed": "0"
            },
            {
            "service": "136",
            "name": "\ud83d\udd25 \ud83c\uddee\ud83c\uddf3 Instagram Followers [\ud83d\ude0dIndian Mix] \ud83d\udc8eLifetime Guarantee \ud83d\ude80Speed:- 20k-30k\/day \ud83d\udce2Start: INSTANT \ud83d\udd25NON DROP -\ud83c\udfaf Highly Recommended",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Indian Followers [ NON DROP ]",
            "rate": "72.9300",
            "min": "10",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "21",
            "name": "\ud83c\udd95 \ud83c\uddee\ud83c\uddf3 REAL Instagram Followers [\ud83d\ude0dINDIAN mix]\ud83d\ude80Speed: 10k-20k\/day- \u2b50[ 6 Month Refill ] + Button\ud83d\udd25Non Drop - \ud83c\udf2aINSTANT",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Indian Followers [ NON DROP ]",
            "rate": "82.1300",
            "min": "50",
            "max": "400000",
            "type": "default",
            "desc": "\ud83c\udf53MOSTLY INDIAN\r\n\r\n\u2b50Start: INSTANT - 3hrs\r\n\u2b50Speed: 10 per day\r\n\u2b50Guarantee: 40 Days Refill [AR]\r\n\r\n\ud83d\udd25NO DROP\ud83d\udd25\r\n[0-8% max]\r\n\r\n\ud83d\udcafREFILL BUTTON ENABLED\ud83d\udcaf\r\n\u274cCANCEL BUTTON ENABLED\u274c\r\n\r\n\ud83c\udf53Giving Supply of this Service\r\n\ud83c\udf53Asap Fetch in your panel\r\n\ud83c\udf53Welcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "22",
            "name": "\ud83c\udd95 \ud83c\uddee\ud83c\uddf3 Instagram Followers [\ud83c\uddee\ud83c\uddf3 INDIAN MIX - Max : 500K - 5 yr Guarantee] \u26a1\ufe0f\u2b50INSTANT",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Indian Followers [ NON DROP ]",
            "rate": "193.8800",
            "min": "10",
            "max": "500000",
            "type": "default",
            "desc": "\ud83c\udf53INSTANT\ud83c\udf53INDIAN MIX\r\n\r\n\u2b50Indian Real Mix\r\n\u2b50Start: INSTANT -1H\r\n\u2b50Speed: 2K-5K\/D\r\n\u2b50Suggest: Min-30k per time\r\n\u2b50365 Auto Refill \/ May No Drop\r\n\r\n\u2b50Drop Ratio: Low",
            "dripfeed": "0"
            },
            {
            "service": "23",
            "name": "\ud83c\udf53 Instagram followers - 60 DAYS REFILL [ HQ ] [ Drop - 1% Only ] \ud83d\udd25NON DROP Start 0-3hr\ud83d\ude80Speed:- 1k-5k\/Day \ud83c\udf53 Recommended \ud83c\udf2a\ufe0f",
            "category": "\u25b6\u25b6 Fully NON DROP Followers",
            "rate": "68.7400",
            "min": "10",
            "max": "200000",
            "type": "default",
            "desc": "Fully Non Drop\r\nDrop 0-2% only\r\nAwesome service\r\n0-3hr start time\r\n60 days refill gurantee\r\nsuper stable followers\r\n\r\nHigh Quality",
            "dripfeed": "0"
            },
            {
            "service": "24",
            "name": "\ud83c\udf53Instagram Followers - 2 year REFILL [ HQ ] [ \ud83d\udc8eDrop - 5% Only ] [ Never drop ] Start: 0-3hr] Stable Lifetime\ud83d\udd25\ud83d\ude80",
            "category": "\u25b6\u25b6 Fully NON DROP Followers",
            "rate": "77.5600",
            "min": "10",
            "max": "1000000",
            "type": "default",
            "desc": "\ud83c\udf53BEST \ud83c\udf53STABLE \ud83c\udf53FAST\r\n\r\n\u2757Provider price 90rs recommend to sell it in 130-150rs\r\n\r\n\ud83d\udd25Never drop after refill\r\n\ud83d\udd25Drop 0-5% only\r\n\ud83d\udd25Amazing services\r\n\ud83d\udd250-3hr start time [ INSTANT ]\r\n\ud83d\udd25lifetime followers\r\n\ud83d\udd25Mostly Indian profiles + ww [HQ]\r\n\ud83d\udd25 365 Days Trusted Guarantee\r\n\r\n\ud83d\udc8eELITE LEVEL users get discount upto 20% on this service.\r\n\ud83d\udd25VIP\/API users welcome to ask for discount on this service .\r\n\ud83c\udf1fBig Resellers also get good offers on this service.\r\n\r\n\ud83c\udf53 Giving Supply of this service\r\n\ud83c\udf53Asap Fetch in your panel\r\n\ud83c\udf53 Welcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "209",
            "name": "Instagram mostly 95% Indian Real Likes Max 10K Slow",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Likes",
            "rate": "9.8800",
            "min": "20",
            "max": "10000",
            "type": "default",
            "desc": "Start:0-30Min\r\nSpeed: 50-100\/Hour\r\nDrop: Less\r\nMin:20\r\nMax:10,000",
            "dripfeed": "0"
            },
            {
            "service": "6",
            "name": "\ud83c\uddee\ud83c\uddf3 Instagram Mostly INDIAN Likes | \ud83c\udf1f BEST + HIGH QUALITY | \ud83d\udd25 0% DROP | \ud83d\ude80Speed:- 1k-3k\/hr | \ud83d\udc8e Lifetime Guarantee | \ud83c\udf53 INSTANT | \ud83d\udd3aMax: 10k | \ud83c\uddee\ud83c\uddf3 INDIAN SPECIAL",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Likes",
            "rate": "29.7400",
            "min": "10",
            "max": "10000",
            "type": "default",
            "desc": "\ud83d\udd25INDIAN EXCLUSIVE\ud83d\udd25\r\n\r\n\ud83d\ude0dStart:- INSTANT\r\n\ud83d\ude0dSpeed:- 1k-2k per hour\r\n\ud83d\ude0d Guarantee:- Lifetime\r\n\ud83d\ude0d Quality:- Best Quality [ Story accounts mix ] in this price\r\n\r\n\ud83d\udce2No Panel giving this INDIAN Quality in this price\r\n\r\n\ud83c\udf53 Giving Supply of this Service\r\n\ud83c\udf53Asap Fetch in your Panel\r\n\ud83c\udf53 Welcome for Discounts",
            "dripfeed": "0"
            },
            {
            "service": "25",
            "name": "\ud83c\uddee\ud83c\uddf3 Instagram 100% INDIAN Power Likes [\ud83c\uddee\ud83c\uddf3Indian Accounts]\ud83d\ude80Speed:2k-3k\/day \ud83d\udd25NON DROP \ud83d\udc8eLifetime Guarantee - \ud83c\udf53INSTANT",
            "category": "\ud83c\uddee\ud83c\uddf3 Instagram Likes",
            "rate": "46.5700",
            "min": "50",
            "max": "10000",
            "type": "default",
            "desc": "\ud83d\udc9c HQ likes\r\n\ud83d\udca7 Non drop usually, but if update came, it will drop upto 10%\r\n\ud83d\ude85 Speed:- 2k+ per hr",
            "dripfeed": "0"
            },
            {
            "service": "154",
            "name": "Instagram Followers | USA | Max 10K | NON DROP | 30D Refill |",
            "category": "\ud83c\uddfa\ud83c\uddf2 Instagram USA",
            "rate": "91.2000",
            "min": "10",
            "max": "10000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "152",
            "name": "Instagram 100% Followers USA\ud83c\uddfa\ud83c\uddf2 FOLLOWERS Best-Service [Max-100K] [REFILL BUTTON ENABLED 30DAYS] [SUPER-INSTANT - 3K\/Day] \u267b",
            "category": "\ud83c\uddfa\ud83c\uddf2 Instagram USA",
            "rate": "296.4000",
            "min": "10",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "153",
            "name": "Instagram 100% [USA\ud83c\uddfa\ud83c\uddf2 Females Followers] Max-100k Speed-10k\/Day R30 [Instant Start]",
            "category": "\ud83c\uddfa\ud83c\uddf2 Instagram USA",
            "rate": "395.2000",
            "min": "10",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "27",
            "name": "\u262a\ufe0f Instagram MUSLIM Verified 1 Comment [ \ud83d\udd25NON DROP\ud83d\udd25 ] [ \u2705BLUE TICK ] [\ud83d\udcccRANDOM ] [ \ud83d\udce3Delivery 0-24 hr ]",
            "category": "\ud83d\udd25 Blue tick comments \u2714 [ Non Drop ]",
            "rate": "100.9300",
            "min": "1",
            "max": "1",
            "type": "custom_comments_package",
            "desc": "\u2705BLUE TICK SERVICE\u2705\r\n\r\n\u262a\ufe0f MUSLIM PROFILE \u262a\ufe0f\r\n\r\n\ud83d\udd25 NON DROP \ud83d\udd25\r\n\r\n\ud83d\udccc RANDOM \ud83d\udccc\r\n\r\n\u26a10-24hrs DELIVERY \u26a1\r\n\r\n\r\n\u26a0\ufe0f\u26a0\ufe0f\u26a0\ufe0fNOTE\u26a0\ufe0f\u26a0\ufe0f\u26a0\ufe0f\r\n\r\n\ud83d\udd39 Some time delivery come within 48 hrs due to overload kindly wait then please don't make pressure on us.\r\n\ud83d\udd39 Some time may be possibility that you not get MUSLIM PROFILE comments . Please Don't mind :)",
            "dripfeed": "0"
            },
            {
            "service": "81",
            "name": "\ud83c\udd95 Instagram Saves (Always Working). Instant [0-1hr]",
            "category": "\ud83d\udc40 Instagram Story \/ Impressions \/ Saves \/ Reach",
            "rate": "3.9000",
            "min": "50",
            "max": "5000",
            "type": "default",
            "desc": "Always working\r\ninstant-1 hour start\r\n\r\nno order will be stuck. guaranteed!!",
            "dripfeed": "0"
            },
            {
            "service": "82",
            "name": "Instagram Story Views - ( All Story ) [ Max - 40K | Speed: 40K\/Day ]",
            "category": "\ud83d\udc40 Instagram Story \/ Impressions \/ Saves \/ Reach",
            "rate": "12.4200",
            "min": "100",
            "max": "40000",
            "type": "default",
            "desc": "username only in link\r\n\r\nnot taking guarantee for full delivery\r\n\r\nNo refund if no delivery\r\n\r\nOrder at your own risk",
            "dripfeed": "0"
            },
            {
            "service": "203",
            "name": "~Instagram Likes No Drop Fast",
            "category": "\u2764 Instagram : Likes [ Guaranteed ]",
            "rate": "6.8400",
            "min": "10",
            "max": "25000",
            "type": "default",
            "desc": "Start;0-5mins\r\nSpeed: 3k-5k\/Hour\r\nMin: 10\r\nMax: 25K\r\nNo Drop",
            "dripfeed": "0"
            },
            {
            "service": "127",
            "name": "ID:480\ud83d\udc4dInstagram Likes - [NO DROP+REAL+AUTOREFILL]",
            "category": "\u2764 Instagram: Auto Likes",
            "rate": "25.0800",
            "min": "10",
            "max": "100000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "221",
            "name": "Facebook Followers | Max 50K | 1k-2k\/Day | Non Drop | 30D Refill |",
            "category": "\u26a1 Facebook: Followers",
            "rate": "107.9200",
            "min": "500",
            "max": "5000",
            "type": "default",
            "desc": "Start: 0-12H\r\nSpeed: 1k\/Day\r\nRefill: 30 days\r\nQuality: Real\r\nDrop: 0-5%",
            "dripfeed": "0"
            },
            {
            "service": "186",
            "name": "Facebook Story Views | Max 5k | 5k\/Day | Instant |",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "63.0800",
            "min": "50",
            "max": "4000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "180",
            "name": "Facebook Video Views | Max 100k | 100k\/Day | Non Drop | Instant | Always Working\ud83d\udd25",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "108.6800",
            "min": "500",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "179",
            "name": "\u265a Facebook \u21aa Video View | \u23f2\ufe0f 3 Sec Watch | \u23e9 1Million Per Day | \u25b6\ufe0f Instant",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "137.4900",
            "min": "500",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "187",
            "name": "Facebook Live Stream Views | 30 Minutes | Instant |",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "183.9200",
            "min": "50",
            "max": "2000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "220",
            "name": "\ud83c\uddee\ud83c\uddf3 Facebook Profile Followers | INDIA | Max 5k | Non Drop | Lifetime Guarantee |",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "244.7200",
            "min": "50",
            "max": "100000",
            "type": "default",
            "desc": "Start: 0-30 min\r\nSpeed: 1-2k\/Day\r\nRefill: Lifetime\r\nQuality: Real Indian Users\r\nAverage: 5 Hour\r\n\r\n\ud83d\udca2Drop Rate: Usually Non Drop, but Can drop 0-5%",
            "dripfeed": "0"
            },
            {
            "service": "188",
            "name": "Facebook Live Stream Views | 60 Minutes | Instant |",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "367.8400",
            "min": "50",
            "max": "2000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "189",
            "name": "Facebook Live Stream Views | 150 Minutes | Instant |",
            "category": "\u26a1 Facebook Live Stream Views",
            "rate": "949.2400",
            "min": "50",
            "max": "2000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "194",
            "name": "Youtube Shorts Views | Max 500k | 10k-20k\/Day | No Refill |",
            "category": "\u2b55\ufe0f Youtube Views :NO REFILL",
            "rate": "44.8400",
            "min": "1000",
            "max": "5000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "195",
            "name": "Youtube Shorts Likes | Max 50k | 5k-10k\/Day | No Refill |",
            "category": "\u2b55\ufe0f Youtube Views :NO REFILL",
            "rate": "50.1600",
            "min": "100",
            "max": "50000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "191",
            "name": "Youtube Views | Real | Max 500K | NON DROP | Lifetime Refill | 2k-5k\/Day |",
            "category": "\u2b55\ufe0fYoutube Views :Guaranteed",
            "rate": "75.2400",
            "min": "200",
            "max": "100000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "219",
            "name": "Youtube Views | Real | Max 1M | 10k\/Day | NON DROP | Lifetime Guarantee |\ud83d\udd25",
            "category": "\u2b55\ufe0fYoutube Views :Guaranteed",
            "rate": "76.0000",
            "min": "200",
            "max": "1000000",
            "type": "default",
            "desc": "Average: 24 hour\r\nStart: 0-3H\r\nSpeed: 3k\/Day\r\nRefill: Lifetime\r\nQuality: High Quality\r\nAverage: 28 hour 24 minutes\r\n\r\n\ud83d\udca2Drop Rate: usually Non Drop,but can drop 0-5% Only",
            "dripfeed": "0"
            },
            {
            "service": "190",
            "name": "YouTube Views | Max 100K | 5k-10k\/Day | Lifetime Guaranteed | \u267b",
            "category": "\u2b55\ufe0fYoutube Views :Guaranteed",
            "rate": "78.2800",
            "min": "200",
            "max": "1000000",
            "type": "default",
            "desc": "",
            "dripfeed": "1"
            },
            {
            "service": "192",
            "name": "YouTube Views | Max 10M | 10k-30k\/Day | Non Drop | Lifetime Guarantee |",
            "category": "\u2b55\ufe0fYoutube Views :Guaranteed",
            "rate": "98.8000",
            "min": "200",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "208",
            "name": "\u2764\ufe0f\ud83d\udc41\ufe0f\u2764\ufe0fYoutube Short Views [10k-20k\/day] Instant Start",
            "category": "\u2b55\ufe0fYoutube Views :Guaranteed",
            "rate": "118.5600",
            "min": "100",
            "max": "100000000",
            "type": "default",
            "desc": "10-20k\/Day\r\nInstant views",
            "dripfeed": "0"
            },
            {
            "service": "193",
            "name": "Youtube Views |10M | NEVER DROP | 40k\/Day | \ud83d\udd25",
            "category": "\u2b55\ufe0fYoutube Views :Guaranteed",
            "rate": "174.8000",
            "min": "1000",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "128",
            "name": "\ud83d\udd25#2 WORKING FAST REEL VIEWS - \ud83c\udfafINSTANT \ud83c\udf53FAST \u2705CHEAP",
            "category": "TESTING CATEGORY",
            "rate": "0.9200",
            "min": "100",
            "max": "20000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "143",
            "name": "\ud83d\ude0dOFFER\ud83d\ude0d - Instagram Video + Reel Views \ud83d\ude0dWorking Stable \u274cCancel Button Enabled\u274c \ud83c\udf84MERRY CHRISTMAS GIFT\ud83c\udf84",
            "category": "TESTING CATEGORY",
            "rate": "1.2400",
            "min": "100",
            "max": "10000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            },
            {
            "service": "144",
            "name": "\ud83d\ude0dOFFER\ud83d\ude0d - Instagram POST+ REEL + IGTV VIEWS \ud83d\udd25SUPER INSTANT \ud83d\udd25\ud83c\udf84MERRY CHRISTMAS GIFT\ud83c\udf84",
            "category": "TESTING CATEGORY",
            "rate": "3.9000",
            "min": "100",
            "max": "10000000",
            "type": "default",
            "desc": "",
            "dripfeed": "0"
            }
            ]
    }
    module.exports=data